---

#Criação de máquinas virtuais
  
- name: -------------------------------------- vault.yml
  include_vars: vault.yml
  no_log: true

- name: ------------------------------------ vmware.yml ------------------------------------
  include_tasks: vmware.yml
  when: 
  - "tipo_servidor == 'VMWARE'"
  - template_so != 'templatew2019'
  - template_so != 'Template_CoreOS_vmx13'

#https://cloud.redhat.com/blog/provision-red-hat-coreos-rhcos-machines-with-custom-v3-ignition-files
#https://guardadoembau.atlassian.net/wiki/spaces/DEVOPS/pages/2714501121/Fedora+CoreOS+-+OVA+e+Ignition
- name: ------------------------------------ vmware-fedora.yml ------------------------------------
  include_tasks: vmware-fedora.yml
  when: 
  - "tipo_servidor == 'VMWARE'"
  - template_so == 'Template_CoreOS_vmx13'

- name: ------------------------------------ vmware-windows.yml ------------------------------------
  include_tasks: vmware-windows.yml
  when: 
  - "tipo_servidor == 'VMWARE'"
  - template_so == 'templatew2019'

- name: ------------------------------------ aws.yml ------------------------------------
  include_tasks: aws.yml
  when: "tipo_servidor == 'AWS'"

- name: ------------------------------------ add-host-to-inventory.yml ------------------------------------
  include_tasks: add-host-to-inventory.yml
  when: 
  - template_so != 'templatew2019'
  - template_so != 'Template_CoreOS_vmx13'

- name: ------------------------------------ add-host-to-inventory-windows.yml ------------------------------------
  include_tasks: add-host-to-inventory-windows.yml
  when: template_so == 'templatew2019'