AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Worker Nodes with Launch Template

Resources:
  # Node Security Group
  NodeSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for EKS worker nodes'
      VpcId: vpc-04746a1f3bd81938d  
      Tags:
        - Key: Name
          Value: NodeSecurityGroup
  ##AWS EKS AMI amazon-eks-node-1.11-v20190220
  # Auto Scaling Group for EKS Worker Nodes
  EKSWorkerNodes:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      DesiredCapacity: '2'
      MaxSize: '2'
      MinSize: '2'
      VPCZoneIdentifier:
        - subnet-01f5f40b90f0b0c52  
      MixedInstancesPolicy:
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: lt-071ed225d2ce996ee  
            Version: '$Latest'
      Tags:
        - Key: Name
          Value: EKSWorkerNode
          PropagateAtLaunch: true

Outputs:
  NodeSecurityGroupID:
    Description: Security Group ID for EKS Worker Nodes
    Value: !Ref NodeSecurityGroup
  WorkerNodeAutoScalingGroupName:
    Description: Auto Scaling Group Name for EKS Worker Nodes
    Value: !Ref EKSWorkerNodes
