AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for Gabriel Manera Workshop

Resources:
  
  # VPC
  WorkshopVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 172.31.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: gabrielmaneraworkshop-vpc

  # Internet Gateway
  WorkshopInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: gabrielmaneraworkshop-igw

  # Attach Internet Gateway to VPC
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref WorkshopVPC
      InternetGatewayId: !Ref WorkshopInternetGateway

  # Public Subnet 1
  PublicSubnetOne:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref WorkshopVPC
      CidrBlock: 172.31.0.0/18
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: gabrielmaneraworkshop-public-subnet1

  # Public Subnet 2
  PublicSubnetTwo:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref WorkshopVPC
      CidrBlock: 172.31.64.0/18
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: gabrielmaneraworkshop-public-subnet2

  # Private Subnet 1
  PrivateSubnetOne:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref WorkshopVPC
      CidrBlock: 172.31.128.0/18
      Tags:
        - Key: Name
          Value: gabrielmaneraworkshop-private-subnet1

  # Private Subnet 2
  PrivateSubnetTwo:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref WorkshopVPC
      CidrBlock: 172.31.192.0/18
      Tags:
        - Key: Name
          Value: gabrielmaneraworkshop-private-subnet2

  # Public Route Table
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref WorkshopVPC
      Tags:
        - Key: Name
          Value: gabrielmaneraworkshop-public-route-table

  # Public Route for Internet Access
  PublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref WorkshopInternetGateway

  # Associate Public Subnet 1 with Public Route Table
  AssociatePublicSubnetOne:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnetOne
      RouteTableId: !Ref PublicRouteTable

  # Associate Public Subnet 2 with Public Route Table
  AssociatePublicSubnetTwo:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnetTwo
      RouteTableId: !Ref PublicRouteTable

Outputs:
  WorkshopVPC:
    Description: "VPC ID"
    Value: !Ref WorkshopVPC
  PublicSubnetOneID:
    Description: "Public Subnet One ID"
    Value: !Ref PublicSubnetOne
  PublicSubnetTwoID:
    Description: "Public Subnet Two ID"
    Value: !Ref PublicSubnetTwo
  PrivateSubnetOneID:
    Description: "Private Subnet One ID"
    Value: !Ref PrivateSubnetOne
  PrivateSubnetTwoID:
    Description: "Private Subnet Two ID"
    Value: !Ref PrivateSubnetTwo
